version: '3.8'

services:
  frontend:
    build:
      context: ./weather-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://34.70.146.172:5001

  backend:
    build:
      context: ./weather-backend
    ports:
      - "5001:5001"
    depends_on:
      - database
    environment:
      - DB_SERVER_URL=http://34.70.146.172:4000

  database:
    build:
      context: ./weather-db
    ports:
      - "4000:4000"
